### ISSUE TITLE
Absturz bei Verbindungsfehler

### ISSUE THREAD

**Issue by AWhiteKnight** [TA2k/ioBroker.nina#14]
Bei fehlender Verbindung stürzt der Adapeter ab.

nina.0 | 2020-03-07 08:58:12.947 | info | (3565) Terminated (NO_ERROR): Without reason
-- | -- | -- | --
nina.0 | 2020-03-07 08:58:12.946 | info | (3565) terminating
nina.0 | 2020-03-07 08:58:12.939 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
nina.0 | 2020-03-07 08:58:12.939 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
nina.0 | 2020-03-07 08:58:12.939 | error | at emitErrorNT (internal/streams/destroy.js:91:8)
nina.0 | 2020-03-07 08:58:12.939 | error | at TLSSocket.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.939 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
nina.0 | 2020-03-07 08:58:12.939 | error | at ClientRequest.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.939 | error | at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
nina.0 | 2020-03-07 08:58:12.939 | error | at Request.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.939 | error | at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
nina.0 | 2020-03-07 08:58:12.939 | error | at Request.request.get [as _callback] (/opt/iobroker/node_modules/iobroker.nina/main.js:181:38)
nina.0 | 2020-03-07 08:58:12.939 | error | (3565) TypeError: Cannot read property 'indexOf' of undefined
nina.0 | 2020-03-07 08:58:12.938 | error | (3565) uncaught exception: Cannot read property 'indexOf' of undefined
nina.0 | 2020-03-07 08:58:12.937 | error | (3565) Request error{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"94.125.29.174","port":443}
nina.0 | 2020-03-07 08:58:12.934 | error | at process._tickCallback (internal/process/next_tick.js:63:19)
nina.0 | 2020-03-07 08:58:12.934 | error | at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
nina.0 | 2020-03-07 08:58:12.934 | error | at emitErrorNT (internal/streams/destroy.js:91:8)
nina.0 | 2020-03-07 08:58:12.934 | error | at TLSSocket.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.934 | error | at TLSSocket.socketErrorListener (_http_client.js:401:9)
nina.0 | 2020-03-07 08:58:12.934 | error | at ClientRequest.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.934 | error | at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
nina.0 | 2020-03-07 08:58:12.934 | error | at Request.emit (events.js:198:13)
nina.0 | 2020-03-07 08:58:12.934 | error | at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
nina.0 | 2020-03-07 08:58:12.934 | error | at Request.request.get [as _callback] (/opt/iobroker/node_modules/iobroker.nina/main.js:181:38)
nina.0 | 2020-03-07 08:58:12.934 | error | (3565) TypeError: Cannot read property 'indexOf' of undefined
nina.0 | 2020-03-07 08:58:12.933 | error | (3565) uncaught exception: Cannot read property 'indexOf' of undefined
nina.0 | 2020-03-07 08:58:12.925 | error | (3565) Request error{"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"94.125.29.174","port":443}

**Comment by AWhiteKnight** [comment]
Adapterversion ist 0.0.15

2. Teil des Logs
host.iobmaster | 2020-03-07 09:00:57.469 | error | Caught by controller[2]: (node:21794) [DEP0018] DeprecationWarning:  Unhandled promise rejections are deprecated. In the future, promise  rejections that are not handled will terminate the Node.js proc
-- | -- | -- | --
host.iobmaster | 2020-03-07 09:00:57.469 | error | Caught by controller[2]: (node:21794) UnhandledPromiseRejectionWarning:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by
host.iobmaster | 2020-03-07 09:00:57.468 | error | Caught by controller[2]: (node:21794) UnhandledPromiseRejectionWarning: undefined
host.iobmaster | 2020-03-07 09:00:57.468 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:63:19)
host.iobmaster | 2020-03-07 09:00:57.468 | error | Caught by controller[1]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
host.iobmaster | 2020-03-07 09:00:57.468 | error | Caught by controller[1]:     at emitErrorNT (internal/streams/destroy.js:91:8)
host.iobmaster | 2020-03-07 09:00:57.467 | error | Caught by controller[1]:     at TLSSocket.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.467 | error | Caught by controller[1]:     at TLSSocket.socketErrorListener (_http_client.js:401:9)
host.iobmaster | 2020-03-07 09:00:57.467 | error | Caught by controller[1]:     at ClientRequest.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.467 | error | Caught by controller[1]:     at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
host.iobmaster | 2020-03-07 09:00:57.467 | error | Caught by controller[1]:     at Request.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.466 | error | Caught by controller[1]:     at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.iobmaster | 2020-03-07 09:00:57.466 | error | Caught by controller[1]:     at Request.request.get [as _callback] (/opt/iobroker/node_modules/iobroker.nina/main.js:181:38)
host.iobmaster | 2020-03-07 09:00:57.466 | error | Caught by controller[1]: TypeError: Cannot read property 'indexOf' of undefined
host.iobmaster | 2020-03-07 09:00:57.466 | error | Caught by controller[0]:     at process._tickCallback (internal/process/next_tick.js:63:19)
host.iobmaster | 2020-03-07 09:00:57.466 | error | Caught by controller[0]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
host.iobmaster | 2020-03-07 09:00:57.465 | error | Caught by controller[0]:     at emitErrorNT (internal/streams/destroy.js:91:8)
host.iobmaster | 2020-03-07 09:00:57.465 | error | Caught by controller[0]:     at TLSSocket.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.465 | error | Caught by controller[0]:     at TLSSocket.socketErrorListener (_http_client.js:401:9)
host.iobmaster | 2020-03-07 09:00:57.465 | error | Caught by controller[0]:     at ClientRequest.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.464 | error | Caught by controller[0]:     at Request.onRequestError (/opt/iobroker/node_modules/request/request.js:881:8)
host.iobmaster | 2020-03-07 09:00:57.464 | error | Caught by controller[0]:     at Request.emit (events.js:198:13)
host.iobmaster | 2020-03-07 09:00:57.464 | error | Caught by controller[0]:     at self.callback (/opt/iobroker/node_modules/request/request.js:185:22)
host.iobmaster | 2020-03-07 09:00:57.463 | error | Caught by controller[0]:     at Request.request.get [as _callback] (/opt/iobroker/node_modules/iobroker.nina/main.js:181:38)
host.iobmaster | 2020-03-07 09:00:57.463 | error | Caught by controller[0]: TypeError: Cannot read property 'indexOf' of undefined

**Comment by TA2k** [comment]
installier mal die 0.0.21 via github da ist das gelöst
