### ISSUE TITLE
Objekt-Browser klappt bei Update auf

### ISSUE THREAD

**Issue by kopierschnitte** [TA2k/ioBroker.nina#19]
Hallo!
Immer wenn sich der Nina-Adapter aktualisiert wird der komplette "Ast" der Instanz (inkl. aller "Zweige") im Objekt-Browser aufgeklappt und ioBroker verschiebt auch den Fokus.
Ist etwas ärgerlich wenn man gerade an einem anderen Objekt arbeitet.

Könnte es ein Bug des Adapters sein oder ist der Fehler evtl. bei ioBroker zu suchen?

Nina-Adapter: v0.0.23
Node.js version 12.18.4
NPM version 6.14.6

**Comment by thost96** [comment]
Der Fehler sollte mit der Version 0.0.24 behoben sein. Zumindest klappt mein "Ast" seit dem Update nicht mehr auf.
