### ISSUE TITLE
Fehlermeldung

### ISSUE THREAD

**Issue by nicknick25** [TA2k/ioBroker.nina#2]
Ich bekomme leider egal in welcher Version diese Fehlermeldung

nina.0 | 2019-07-27 15:56:04.963 | error | {}
-- | -- | -- | --
nina.0 | 2019-07-27 15:56:04.961 | error | {"errno":"EPROTO","code":"EPROTO","syscall":"write"}

**Comment by Steff42** [comment]
Moin,
bekomme die gleiche Fehlermeldung wie @nicknick25 und zusätzlich beim stoppen der Instanz noch folgendes:
![image](https://user-images.githubusercontent.com/35137293/62003814-f0489500-b11c-11e9-87ea-fd038eabdfc1.png)
Node.js
v10.16.0
NPM
6.9.0
Gruß Steffen

**Comment by nicknick25** [comment]
@Steff42 sieht bei mir nach dem stoppen genauso aus

**Comment by Steff42** [comment]
Habe heute nochmals installiert, da nun aussagekräftigere Fehlermeldungen generiert werden sollen. Nun habe ich diesen Fehler:
![image](https://user-images.githubusercontent.com/35137293/62376019-fa64fc00-b53f-11e9-8559-3eb02e34ea22.png)
Der Fehler beim Stoppen hat sich nicht verändert.
AGS beim mir die 08118
Gruß Steffen

**Comment by nicknick25** [comment]
Bei mir genau der selbe Fehler. Beim stoppen hat sich nichts verändert.

**Comment by Nuggelbeb** [comment]
Bei mir genau der selbe Fehler.

`

nina.0 | 2019-08-03 13:26:05.316 | info | undefined
-- | -- | -- | --
nina.0 | 2019-08-03 13:26:05.315 | error | SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-08-03 13:26:05.313 | error | {"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-08-03 13:26:05.308 | info | undefined
nina.0 | 2019-08-03 13:26:05.307 | error | SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-08-03 13:26:05.298 | error | {"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-08-03 13:26:05.266 | info | undefined
nina.0 | 2019-08-03 13:26:05.265 | error | SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-08-03 13:26:05.259 | error | {"errno":"EPROTO","code":"EPROTO","syscall":"write"}

`

**Comment by vaaarg** [comment]
nina.0 | 2019-09-02 09:59:45.798 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token u in JSON at position 0 {}
-- | -- | -- | --
nina.0 | 2019-09-02 09:59:45.798 | error | Request error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-09-02 09:59:45.797 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-09-02 09:59:45.797 | error | Request error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-09-02 09:59:45.796 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-09-02 09:59:45.795 | error | Request error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-09-02 09:59:45.793 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-09-02 09:59:45.792 | error | Request error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
nina.0 | 2019-09-02 09:59:45.782 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token u in JSON at position 0 {}
nina.0 | 2019-09-02 09:59:45.779 | error | Request error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}

**Comment by EvilEls** [comment]
here too
did not change anything.
reset of adapter doesn't help


```
nina.0 | 2019-09-25 23:49:29.295 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token  in JSON at position 0 {}
-- | -- | -- | --
nina.0 | 2019-09-25 23:49:29.291 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token  in JSON at position 0 {}
nina.0 | 2019-09-25 23:49:29.283 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token  in JSON at position 0 {}
nina.0 | 2019-09-25 23:49:29.271 | warn | Website sends unparsable data, you can ignore if it happens only once: SyntaxError: Unexpected token  in JSON at position 0 {}
nina.0 | 2019-09-25 23:49:28.610 | info | starting. Version 0.0.8 in /opt/iobroker/node_modules/iobroker.nina, node: v10.16.3
```

**Comment by TA2k** [comment]
error{"errno":"EPROTO","code":"EPROTO","syscall":"write"} tritt bei debian Buster auf:
siehe https://forum.iobroker.net/topic/23866/aufruf-nina-gefahrenmeldung-adapter
unparsable data passiert manchmal wenn nina falsche Daten zurückgibt.
