### ISSUE TITLE
Logo aktualisieren (hat weißen Hintergrund)

### ISSUE THREAD

**Issue by klein0r** [TA2k/ioBroker.nina#20]
Sollte ein transparentes PNG sein

**Comment by thost96** [comment]
Der Issue sollte durch #41 von gestern Abend erledigt sein. Damit dies im ioBroker wirksam wird, fehlt allerdings noch ein Adapter Update auf 0.0.24 passend zur Readme.

**Comment by thost96** [comment]
@TA2k der Issue kann durch den Release 0.0.24 auch geschlossen werden.
