### ISSUE TITLE
Link zu AGS-Suche tauschen / erweitern

### ISSUE THREAD

**Issue by klein0r** [TA2k/ioBroker.nina#21]
Mit dem aktuellen JSON kann bestimmt kaum jemand etwas anfangen. Daher entweder eine Suche implementieren oder hierher verlinken: https://www.statistikportal.de/de/gemeindeverzeichnis

**Comment by Feuer-sturm** [comment]
Ich hab es mal in der Readme angepasst und einen Pull request gestellt: https://github.com/TA2k/ioBroker.nina/pull/24
