### ISSUE TITLE
(4465) Cannot reach https://warnung.bund.de/bbk.status/status_

### ISSUE THREAD

**Issue by RicoAeckerle** [TA2k/ioBroker.nina#22]
nina.0 | 2021-01-03 02:31:00.668 | warn | (4465) Cannot reach https://warnung.bund.de/bbk.status/status_033510180000.json Server. Statuscode: 404
-- | -- | -- | --

Die AGS habe ich mir hier her geholt: hoffe das ist richtig, weil es über den Link nicht ging.
https://www.riserid.eu/glossarbegriffe/source/default/term/amtlicher-gemeindeschluessel-ags/

**Comment by bertl83** [comment]
Any news? I ve the same error

**Comment by MotschaM** [comment]
mir geht es auch so, es funktioniert auch nicht mit deinem Link @RicoAeckerle

**Comment by RicoAeckerle** [comment]
@MotschaM bei mir geht es auch nicht aber die AGs habe ich mir dort raus gesucht. Da diese aber vom code anders erwartet werden oder es die Seiten so nicht mehr gibt geht es halt nicht weiter

**Comment by Feuer-sturm** [comment]
Wenn ich zwei AGS bei mir eintrage bekomme ich den gleichen Fehler. Wenn ich nur einen AGS eintrage sehe ich den Fehler nicht im Log.
Habt ihr mehrere AGS bei euch eingetragen?

**Comment by Feuer-sturm** [comment]
Ich hab mir mal eine willkürliche Stadt rausgegriffen (Bremen) und den AGS hier für Bremen herausgesucht (https://www.statistikportal.de/de/gemeindeverzeichnis) 

Wenn man den AGS dann in den Link einbaut bekommt man auch eine Rückmeldung.
https://warnung.bund.de/bbk.status/status_040110000000.json
Die States in ioBroker werden für Bremen erzeugt und zwei Warnungen werden angezeigt.


Wenn ich jetzt Hannover als nächstes nehme https://warnung.bund.de/bbk.status/status_032410010000.json kommt wieder eine 404 obwohl laut https://warnung.bund.de/meldungen Warnungen für Hannover vorliegen.

**Comment by thost96** [comment]
Hallo zusammen,

habe dasselbe auch für Hannover bemerkt. Die AGS Nummer muss auf die ersten 5 Zahlen gekürzt werden, dann klappt die Abfrage auch und liefert passende Ergebnisse. Ich mache mich dazu mal an einen PR.

**Comment by thost96** [comment]
Edit 17.02.2021:
In der Version 0.0.24 wurde dies angepasst, sodass die AGS automatisch auf fünf Zahlen gekürzt wird. @Feuer-sturm somit sollten deine Tests jetzt auch funktionieren. 

Der Issue sollte damit auch gelöst sein.
