### ISSUE TITLE
Erros in Log & Verbunden mit nina = falsch

### ISSUE THREAD

**Issue by huperis** [TA2k/ioBroker.nina#7]
After installation and configuration of the adapter, there are erros in the log file and the status of "Verbunden mit nina" is wrong.

> 2019-10-13 12:58:50.808 - error: nina.0 (9843) Request
> error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
> 2019-10-13 12:58:50.810 - error: nina.0 (9843) SyntaxError: Unexpected
> token u in JSON at position 0 {}
> 2019-10-13 12:58:50.814 - error: nina.0 (9843) Request
> error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
> 2019-10-13 12:58:50.815 - error: nina.0 (9843) SyntaxError: Unexpected
> token u in JSON at position 0 {}
> 2019-10-13 12:58:50.817 - error: nina.0 (9843) Request
> error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
> 2019-10-13 12:58:50.818 - error: nina.0 (9843) SyntaxError: Unexpected
> token u in JSON at position 0 {}
> 2019-10-13 12:58:50.831 - error: nina.0 (9843) Request
> error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
> 2019-10-13 12:58:50.832 - error: nina.0 (9843) SyntaxError: Unexpected
> token u in JSON at position 0 {}
> 2019-10-13 12:58:50.833 - error: nina.0 (9843) Request
> error{"errno":"EPROTO","code":"EPROTO","syscall":"write"}
> 2019-10-13 12:58:50.834 - error: nina.0 (9843) SyntaxError: Unexpected
> token u in JSON at position 0 {}

**Comment by MotschaM** [comment]
Bei mir ist es das selbe wie bei huperis!!

**Comment by TA2k** [comment]
Siehe Beitrag 1 im thread für den Adapter

**Comment by huperis** [comment]
> 
> 
> Siehe Beitrag 1 im thread für den Adapter

Danke, erledigt.
