### ISSUE TITLE
Problem mit RegEx bei AGS Nummern

### ISSUE THREAD

**Issue by ToGe3688** [TA2k/ioBroker.nina#9]
Wenn eine AGS Nummer auf 0 endet wird diese durch die RegEx Prüfung mit entfernt und Einträge aus den JSON Daten daher nichtmehr erkannt. Eine schnelle Lösung ist die AGS Nummer ohne die 0 am Ende im Adapter zu nutzen, es sollte allerdings vom Script auch erkannt werden z.B. durch eine Prüfung der Länge der AGS. Ein Beispiel wäre die 05570 in den angehängten JSON Daten. 

[gefahrendurchsagen.zip](https://github.com/TA2k/ioBroker.nina/files/3896365/gefahrendurchsagen.zip)

**Comment by TA2k** [comment]
Ist gelöst mir version 0.0.14
